#!/usr/bin/env bash
# Generate all IDL bindings (single source of truth for justfile, CI, and preflight).

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# Select the completed build's actual executable once, rather than running Cargo
# for each IDL. Rendering and validation still occur for every output each pass.
BUILD_JSON="$(mktemp)"
trap 'rm -f "$BUILD_JSON"' EXIT
cargo build --locked -p idl_codegen --bin idl_codegen --message-format=json > "$BUILD_JSON"
CODEGEN_BIN="$(python3 tools/ci/cargo_artifact.py "$BUILD_JSON" idl_codegen)"

run_codegen() {
  "$CODEGEN_BIN" "$@"
}

run_codegen --in idl/harness/ping_harness.toml --out kernel_api/src/generated/ping_harness.generated.rs
run_codegen --in idl/harness/capsule_control_v0.toml --out kernel_api/src/generated/capsule_control_v0.generated.rs
run_codegen --in idl/harness/capsule_control_v0.toml --out tools/capsule/generated/capsule_control_v0.h
run_codegen --in idl/harness/echo_harness_v0.toml --out kernel_api/src/generated/echo_harness_v0.generated.rs
run_codegen --in idl/portals/file_picker_v1.toml --out kernel_api/src/generated/portal_file_picker.generated.rs
run_codegen --in idl/portals/clipboard_v1.toml --out kernel_api/src/generated/portal_clipboard.generated.rs
run_codegen --in idl/portals/notifications_v1.toml --out kernel_api/src/generated/portal_notifications.generated.rs
run_codegen --in idl/portals/screen_capture_v1.toml --out kernel_api/src/generated/portal_screen_capture.generated.rs
run_codegen --in idl/portals/desktop_session_v1.toml --out kernel_api/src/generated/desktop_session_v1.generated.rs
run_codegen --in idl/harness/input_v1.toml --out kernel_api/src/generated/input_v1.generated.rs
run_codegen --in idl/services/desktop_focus_v1.toml --out kernel_api/src/generated/desktop_focus_v1.generated.rs
run_codegen --in idl/services/desktop_surface_v1.toml --out kernel_api/src/generated/desktop_surface_v1.generated.rs
run_codegen --in idl/portals/desktop_editor_session_v1.toml --out kernel_api/src/generated/desktop_editor_session_v1.generated.rs
run_codegen --in idl/portals/desktop_artifact_v1.toml --out kernel_api/src/generated/desktop_artifact_v1.generated.rs
run_codegen --in idl/harness/domain_manager_v1.toml --out kernel_api/src/generated/domain_manager_v1.generated.rs
run_codegen --in idl/harness/gpu_quarantine_v1.toml --out kernel_api/src/generated/gpu_quarantine_v1.generated.rs
run_codegen --in idl/harness/net_v1.toml --out kernel_api/src/generated/net_v1.generated.rs
run_codegen --in idl/harness/block_v1.toml --out kernel_api/src/generated/block_v1.generated.rs
run_codegen --in idl/harness/shmem_control_v1.toml --out kernel_api/src/generated/shmem_control_v1.generated.rs
run_codegen --in idl/services/store_service_v1.toml --out kernel_api/src/generated/store_service_v1.generated.rs
run_codegen --in idl/harness/trace_service_v1.toml --out kernel_api/src/generated/trace_service_v1.generated.rs
run_codegen --in idl/harness/echo_harness_v1.toml --out kernel_api/src/generated/echo_harness_v1.generated.rs
run_codegen --in idl/harness/trace_service_v2.toml --out kernel_api/src/generated/trace_service_v2.generated.rs
run_codegen --in idl/services/semantic_state_v1.toml --out kernel_api/src/generated/semantic_state_v1.generated.rs
run_codegen --in idl/harness/semantic_store_v1.toml --out kernel_api/src/generated/semantic_store_v1.generated.rs
run_codegen --in idl/harness/agent_task_v1.toml --out kernel_api/src/generated/agent_task_v1.generated.rs
run_codegen --in idl/services/execution_fabric_v1.toml --out kernel_api/src/generated/execution_fabric_v1.generated.rs
run_codegen --in idl/harness/echo_harness_v0.toml --out sdk/src/generated/harness_echo_v0.rs --lang wasm-imports
run_codegen --in idl/services/semantic_state_v1.toml --out sdk/src/generated/services_semantic_state_v1.rs --lang wasm-imports
run_codegen --in idl/harness/shmem_control_v1.toml --out sdk/src/generated/harness_shmem_control_v1.rs --lang wasm-imports
run_codegen --in idl/services/semantic_state_v1.toml --out services/native_runner/src/generated/services_semantic_state_v1_host.rs --lang wasm-host
run_codegen --in idl/harness/shmem_control_v1.toml --out services/native_runner/src/generated/harness_shmem_control_v1_host.rs --lang wasm-host
run_codegen --in idl/harness/echo_harness_v1.toml --out services/native_runner/src/generated/harness_echo_v1_host.rs --lang wasm-host
run_codegen --in idl/harness/trace_service_v2.toml --out services/native_runner/src/generated/harness_trace_v2_host.rs --lang wasm-host

# The aggregator is rendered every pass too; preserve its mtime when identical.
python3 - <<'PY'
from pathlib import Path

path = Path('services/native_runner/src/generated/mod.rs')
rendered = b'''\
//! Generated host bindings for the native WASM runner.
//! Regenerated by tools/ci/run_codegen.sh; do not edit by hand.
#![allow(dead_code)]

pub mod harness_echo_v1_host;
pub mod harness_shmem_control_v1_host;
pub mod harness_trace_v2_host;
pub mod services_semantic_state_v1_host;
'''
try:
    existing = path.read_bytes()
except FileNotFoundError:
    existing = None
if existing != rendered:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(rendered)
PY

echo "CODEGEN: ok"
